# Generated by Django 4.0.5 on 2022-06-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Identificador Único de Producto')),
                ('name', models.CharField(max_length=126, verbose_name='Nombre')),
                ('description', models.CharField(max_length=512, verbose_name='Descripción')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
