# Generated by Django 4.0.5 on 2022-06-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=30, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
